# Generated by Django 3.2.8 on 2021-11-23 03:49

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='sign',
            field=models.CharField(default=users.models.createSignature, max_length=50, unique=True),
        ),
    ]
