# Generated by Django 3.2.8 on 2021-11-23 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_sign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='sign',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
