# Generated by Django 3.2.8 on 2021-12-04 17:39

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_sign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='ssn',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=20)),
        ),
    ]
