# Generated by Django 3.2.8 on 2021-11-03 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ballot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ballot_title', models.TextField(default='', max_length=200)),
                ('ballot_description', models.TextField(blank=True, default='', max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('due_date', models.DateTimeField(verbose_name='due date')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(max_length=200)),
                ('ballot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ballots.ballot')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ballots.question')),
            ],
        ),
    ]
