# Generated by Django 3.2.8 on 2021-11-23 04:01

import ballots.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ballots', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ballot',
            name='pub_date',
            field=models.DateTimeField(default=ballots.models.now_plus_7, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='choice_text',
            field=models.TextField(max_length=200),
        ),
        migrations.CreateModel(
            name='CastVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter_signature', models.CharField(max_length=50, unique=True)),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ballots.choice')),
            ],
        ),
    ]
