# Generated by Django 3.2.8 on 2021-11-17 04:40

import ballots.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ballots', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ballot',
            name='ballot_description',
            field=models.TextField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='ballot',
            name='ballot_title',
            field=models.TextField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='ballot',
            name='due_date',
            field=models.DateTimeField(default=ballots.models.now_plus_30, verbose_name='due date'),
        ),
        migrations.AlterField(
            model_name='ballot',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='choice_text',
            field=models.TextField(max_length=200),
        ),
    ]
