# Generated by Django 3.2.8 on 2021-11-18 17:17

import ballots.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ballots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ballot',
            name='district',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='ballot',
            name='due_date',
            field=models.DateTimeField(default=ballots.models.now_plus_30, verbose_name='due date'),
        ),
        migrations.AlterField(
            model_name='ballot',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published'),
        ),
    ]
