# Generated by Django 3.2.8 on 2021-11-27 19:26

import ballots.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ballots', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CastBallot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='ballot',
            name='pub_date',
            field=models.DateTimeField(default=ballots.models.now_plus_7, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='votes',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.CreateModel(
            name='VoteRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter_signature', models.CharField(max_length=50)),
                ('assoc_ballot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ballots.ballot')),
            ],
        ),
        migrations.CreateModel(
            name='CastVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ballot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ballots.castballot')),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ballots.choice')),
            ],
        ),
        migrations.AddField(
            model_name='castballot',
            name='assoc_ballot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ballots.ballot'),
        ),
    ]