# Generated by Django 3.2.8 on 2021-11-17 19:07

import ballots.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ballots', '0002_auto_20211116_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ballot',
            name='pub_date',
            field=models.DateTimeField(default=ballots.models.now_plus_7, verbose_name='date published'),
        ),
    ]
